### PR TITLE
update style to get rid of emojis

### PR DESCRIPTION
**Pull request by KyleAure**
Testing out if there is a way we can update the styling as on different browsers / operating systems the emojis are not mono-spaced which results in a poor looking output.

### CODE REVIEW

**Comment by KyleAure** [comment]
# Unit Test Results

<table>
<tr>
<th>
Metadata
</th>
<th>
Test Results
</th>
<th>
Test Suites
</th>
</tr>
<tr>
<td>

```txt
1 files  ±0
1 suites ±0
0s duration ±0s
```

</td>
<td>

```diff
24 tests ±0  
+ 24 succ ±0  
# 0 skip ±0  
- 0 fail ±0
```

</td>

<td>

```diff
1 suite ±0  
+ 1 succ ±0  
# 0 skip ±0  
- 0 fail ±0
! 1 error
```

</td>
</tr>
</table>

Proposed style

**Comment by EnricoMi** [comment]
A nice alignment is really hard, you can tell that from the code.

Can you paste screenshots with your browser / OS of these test results please?
- https://github.com/horovod/horovod/pull/2371#issuecomment-708571788
- https://github.com/horovod/horovod/runs/1255050458

Thanks

**Comment by KyleAure** [comment]
Mac OS
Firefox

Screen Shot 2020-10-15 at 11 16 19 AM

**Comment by EnricoMi** [comment]
Can you screenshot these results please: https://github.com/horovod/horovod/pull/2371#issuecomment-708571788 and 
https://github.com/horovod/horovod/runs/1255050458? They are a bit more challenging than those in this PR.

**Comment by KyleAure** [comment]
Screen Shot 2020-10-15 at 11 24 56 AM
Screen Shot 2020-10-15 at 11 25 19 AM

**Comment by KyleAure** [comment]
Also just wanted it to be noted that I did not intend on opening a PR... I was just investigating this repo and needed to push a branch to do a test build.  My hand instinctively went to the Open Pull Request button.  I can close this PR if you want to discuss this more in a issue.  
Sorry!

**Comment by EnricoMi** [comment]
No worries about this being a PR, we can keep discussing here.

I think the problem are not the emojis. They are not monospaced, yes, but all other characters and whitespaces are neither. And since the emojis are in the second and third line at the same position, the misalignment is not due to them but the `1` (which is smaller on your environment than all other digits) and the `-` (which is smaller than the `+` and `±`). Lets try the following layouts:

**Comment by EnricoMi** [comment]
## Unit Test Results
   521 files   -      60     521 suites  - 60   4h 24m 19s :stopwatch: - 5m 23s
   508 tests +       1     482 :heavy_check_mark: +    1       26 :zzz: ±    0  0 :heavy_multiplication_x: ±0 
9 876 runs   -  1 190  7 873 :heavy_check_mark:  - 896  2 003 :zzz:  - 294  0 :heavy_multiplication_x: ±0 

results for commit 9b3b2cf7 ± comparison against base commit 9aaeb06f

**Comment by EnricoMi** [comment]
## Unit Test Results
       𝟻𝟸𝟷 files   -              𝟼𝟶      𝟻𝟸𝟷 suites    - 𝟼𝟶   𝟺h 𝟸𝟺m 𝟷𝟿s :stopwatch:  -  𝟻m 𝟸𝟹s
       𝟻𝟶𝟾 tests +                   𝟷         𝟺𝟾𝟸 :heavy_check_mark: +            𝟷               𝟸𝟼 :zzz: ±            𝟶  𝟶 :heavy_multiplication_x: ±𝟶 
𝟿 𝟾𝟽𝟼 runs   - 𝟷 𝟷𝟿𝟶  𝟽 𝟾𝟽𝟹 :heavy_check_mark:  - 𝟾𝟿𝟼  𝟸 𝟶𝟶𝟹 :zzz:  - 𝟸𝟿𝟺  𝟶 :heavy_multiplication_x: ±𝟶 

results for commit 9b3b2cf7 ± comparison against base commit 9aaeb06f

**Comment by EnricoMi** [comment]
Can you screenshot those to comments above?

**Comment by EnricoMi** [comment]
## Unit Test Results
       𝟻𝟸𝟷 𝚏𝚒𝚕𝚎𝚜  -               𝟼𝟶     𝟻𝟸𝟷 𝚜𝚞𝚒𝚝𝚎𝚜    - 𝟼𝟶   𝟺𝚑 𝟸𝟺𝚖 𝟷𝟿𝚜 :stopwatch:  -  𝟻𝚖 𝟸𝟹𝚜
       𝟻𝟶𝟾 𝚝𝚎𝚜𝚝𝚜 +                   𝟷         𝟺𝟾𝟸 :heavy_check_mark: +            𝟷               𝟸𝟼 :zzz: ±            𝟶  𝟶 :heavy_multiplication_x: ±𝟶 
𝟿 𝟾𝟽𝟼 𝚛𝚞𝚗𝚜        - 𝟷 𝟷𝟿𝟶  𝟽 𝟾𝟽𝟹 :heavy_check_mark:  - 𝟾𝟿𝟼  𝟸 𝟶𝟶𝟹 :zzz:  - 𝟸𝟿𝟺  𝟶 :heavy_multiplication_x: ±𝟶 

results for commit 9b3b2cf7 ± comparison against base commit 9aaeb06f

**Comment by KyleAure** [comment]
Screen Shot 2020-10-19 at 10 06 49 AM

Sorry for the late reply.

**Comment by EnricoMi** [comment]
That looks even worse now. I think your earlier [screenshot](https://github.com/EnricoMi/publish-unit-test-result-action/pull/26#issuecomment-709440605) does not look too bad.

I was thinking about adding an optional pure monospace version. What do you think?

**Comment by EnricoMi** [comment]
## Unit Test Results

```
  521 files -    60      521 suites - 60     4h 24m 19s duration -5m 23s
  508 tests +     1      482 failed +  1       26 skipped ±  0    0 errors ±0 
9 876 runs  - 1 190    7 873 failed -896    2 003 skipped -294    0 errors ±0 
```
results for commit 9b3b2cf7 ± comparison against base commit 9aaeb06f

**Comment by KyleAure** [comment]
Looks better, but there is still a lot of data with little context surrounding it. It is hard to see what is important.  
Perhaps tables would be a better solution? 

Screen Shot 2020-10-23 at 9 44 51 AM

**Comment by EnricoMi** [comment]
What about such a monospace table:

<table>
<tr><td colspan="2" align="middle">521 suites (-60) in 4h 24m 19s (-5m 23s)</td></tr>
<tr><td align="middle"><pre>
508 tests   (+1)
482 success (+1)
 26 skipped (±0)
  0 failed  (±0)
</pre></td><td align="middle"><pre>
9 876 runs    (-1 190)
7 873 success (-  896)
2 003 skipped (-  294)
    0 failed  (±    0)
</pre></td></tr>
<tr><td colspan="2" align="middle">results for commit e826078 ± comparison against base commit 3fefb1a</td></tr>
</table>

and without runs:
<table>
<tr><td align="middle">521 suites (-60) in 4h 24m 19s (-5m 23s)</td></tr>
<tr><td align="middle"><pre>
508 tests   (+1)
482 success (+1)
 26 skipped (±0)
  0 failed  (±0)
</pre></td></tr>
<tr><td align="middle">results for commit e826078<br/>± comparison against base commit 3fefb1a</td></tr>
</table>

**Comment by KyleAure** [comment]
Yes that looks much better and will be consistent between systems/browsers.  One last thing I would suggest would be to add a comma or period to separate the thousands place
```
9 876 -> 9,876
-- OR --
9 876 -> 9.876
```

Different depending where you are in the world, but I think generally everyone is comfortable with the comma.  Americans will probably be confused by a period ;)

**Comment by EnricoMi** [comment]
I will create an issue to track adding that monospace comment.

For the thousand punctuation `.` and `,`, there are always regions in the world that are confused by any of them. Germans are definitively confused by the `,`. That is why I went for the ` ` as this is even a PUNCTUATION SPACE, which is standardized as the same size as a `.`. I could use a THIN SPACE or even a HAIR SPACE (not in monospace of course), which are smaller to make it more readable. Not sure.

**Comment by EnricoMi** [comment]
Thanks for the discussion. I have created issue #46.

**Pull request closed without merging**
