### PR TITLE
Option to disable status check

### LINKED ISSUE #491: How do I disable checks? i.e. just get red/green step/job/workflow based on unit test results
How can I disable anything but red/green status of the step using this action?

### I want

- Failing tests to fail my step/job/workflow. ❌ 
- Green tests to pass my step/job/workflow. ✅ 

### I do not want

- PR annotations ❌
- PR checks ❌
- PR comment ✅
- PR job summary ✅
- PR check summary ✅

### Here's what I have tried:
```yaml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@283dea176069279a9076e77b548668a8e4f0c31b # v2.9.0
        with:
          files: "junitreport/*.xml"
          check_name: ${{ matrix.test }} results
          # This job should fail if tests fail:
          fail_on: "test failures"
          action_fail: true
          # This job should not upload test results to the PR (as it's grouped across these "matrix" jobs in the next "publish" job):
          check_run_annotations: none
          job_summary: false
          comment_mode: off
```

I thought `action_fail` was there for this particular purpose?

But when I run the above, I get for example this (at the moment I have an invalid path to my junit xml):
```shell
Publish Test Results
  2023-09-20 06:48:51 +0000 - publish -  INFO - Available memory to read files: 34.3 GiB
  2023-09-20 06:48:51 +0000 - publish - WARNING - Could not find any files for junitreport/*.xml
  2023-09-20 06:48:51 +0000 - publish -  INFO - Finished reading 0 files in 0.00 seconds
  2023-09-20 06:48:52 +0000 - publish -  INFO - Publishing neutral results for commit b13c20a54a9858a83a7827d621e724a2b4666f6b
  2023-09-20 06:48:54 +0000 - publish -  INFO - Created check https://github.com/my-org/my-repo/runs/123123123123
  2023-09-20 06:48:54 +0000 - publish -  INFO - Commenting on pull requests disabled
  Warning: Could not find any files for junitreport/*.xml
```

Also, as I tried to denote with ❌ / ✅ above,  I am still getting "PR checks" and annotations.

### PR DESCRIPTION
**Pull request by TurnrDev**
Adds an option to disable checks. Fixes #491.

### CODE REVIEW

**Comment by EnricoMi** [comment]
Thanks for this feature, I have fixed and extended the tests. I think the publish logic should also look different.

Please inspect my changes.

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by TurnrDev** [comment]
> Thanks for this feature, I have fixed and extended the tests. I think the publish logic should also look different.
> 
> Please inspect my changes.

Thank you, I will take a look at some point this week.

**Review by TurnrDev — COMMENTED** [review]
LGTM

**Comment by TurnrDev** [comment]
I tried to use this today pinned to the latest commit and it didn't work as expected. I assume this is due the [container](https://github.com/EnricoMi/publish-unit-test-result-action/pkgs/container/publish-unit-test-result-action) not being built. Is there an ETA on when we can expect the next build? :)

**Comment by EnricoMi** [comment]
You can try this directly from master via:

    uses: EnricoMi/publish-unit-test-result-action/composite@master

The `/composite` is doing the magic here.

**Pull request merged**
