### PR TITLE
Update links on comments to point to the latest version

### PR DESCRIPTION
**Pull request by ofek**
I chose to pin it strictly like the way it was but let me know if you would prefer a major version like `v2` instead!

### CODE REVIEW

**Comment by EnricoMi** [comment]
What was the problem that the old version caused you?

**Comment by ofek** [comment]
I noticed it because the documentation is outdated

**Comment by ofek** [comment]
Is this okay so the links point to newer documentation?

**Comment by EnricoMi** [comment]
I haven't moved this version as it impacts a lot of files (as you can see). The referenced section (the icons) has not changed since 1.20, so it is "up-to-date". But I can understand that coming from the latest version jumping to v1.20 documentation has its limitations.

Let me sketch something out to reduce the fallout. Then this could be kept in sync with `action.yaml`.

**Comment by EnricoMi** [comment]
I have added the version as a variable to some tests and replaced it in those annotation files. This should reduce the diff when changing the version in the future.

**Comment by ofek** [comment]
Awesome, thanks!

**Comment by ofek** [comment]
Is this good to merge?

**Comment by EnricoMi** [comment]
Done, thanks!

**Comment by ofek** [comment]
Thank you!

**Pull request merged**
