### PR TITLE
Use the built-in venv module and enable venv caching

### PR DESCRIPTION
**Pull request by wildmichael**
Creation of the venv in the composite version of the module takes quite  long time. This change enables caching of the `venv/` directory by the calling workflow. Unfortunately, the composite action cannot perform the caching itself because `uses:` is not supported for composite actions. The `README.md` now explains how this can be done, however.

### CODE REVIEW

**Comment by EnricoMi** [comment]
Thanks for the feedback.

Initially I wasn't sure whether it would be worthwhile to install the venv in the first place. Then I saw it is quite quick (a few seconds overhead) so I went for it. If it is sometimes slow, why not removing it completely?

**Comment by wildmichael** [comment]
The venv itself isn't so much a problem, but the `pip install` took around a minute. Not using a venv worries me a bit because the `pip install` could pollute or subtly corrupt the caller's Python installation by upgrading packages. Making it optional could work, but then caching would be even more difficult.

The whole thing is a bit dissatisfying, it would be preferable if the action could do the caching itself. But it appears that GitHub doesn't support that for composite actions. The alternative would be a JavaScript action, maybe modeled after `action/setup-python`.

**Comment by EnricoMi** [comment]
It is easy to "isolate" the action in its own workflow by uploading the test result files in the CI workflow and downloading them in the publish workflow again.

**Comment by wildmichael** [comment]
Ah, yes, but then it should be obvious from the docs that it might be a necessary to split testing and publishing into separate jobs. Would `action/setup-python` properly cache the custom-installed packages?

**Comment by wildmichael** [comment]
Ugh, and I just realized that Mac OS doesn't have `realpath`.

**Comment by EnricoMi** [comment]
The `action/setup-python` does not provide any caching, but caching `pip` can be done via `actions/cache`: https://github.com/actions/cache/blob/main/examples.md#python---pip.

I agree, if I am removing `venv` from the composite action, then it must be stated in the docs explicitly that the action runs `pip install --upgrade pip` and `pip install --upgrade -r python/requirements.txt`, which might interfere with subsequent python actions, and splitting the workflows would be the solution to isolate the action. I would also provide a caching example.

**Comment by EnricoMi** [comment]
I have sketched out the pip caching in #127:
- with cold cache: https://github.com/EnricoMi/publish-unit-test-result-action/runs/2491747336?check_suite_focus=true#step:6:14
- with hot cache: https://github.com/EnricoMi/publish-unit-test-result-action/runs/2491806869?check_suite_focus=true#step:6:14

The PIP cache avoids the download, but the packages still need to be installed. This cuts startup down from 8s to 5s, while restoring the cache adds one or two seconds. Caching the installed python setup would avoid the package installation but restoring that many files is probably not faster than caching the download.

If the download is really slow, than the pip cache helps to stabilise startup times. Running this on GitHub does not seem to be worth the effort.

**Comment by wildmichael** [comment]
Have you tried on a Windows runner? Ubuntu is fast, but Windows takes 48s just for the publishing. See e.g. this run: https://github.com/wildmichael/cpp_project_template/runs/2483178025?check_suite_focus=true

**Comment by EnricoMi** [comment]
Yes, Windows is embarrassingly slow when installing Python dependencies. I managed to cut the startup time on Windows down from 35 seconds to 10 seconds: https://github.com/EnricoMi/publish-unit-test-result-action/runs/2493519608?check_suite_focus=true

It is all described in the README in #127. It is not simple, but maybe worth the effort.

**Comment by wildmichael** [comment]
I can well live with caching the pip cache :-) I think we can close this PR, right?

**Comment by EnricoMi** [comment]
Thanks for the discussion and good code inspirations!

**Pull request closed without merging**
